import * as cdk from 'aws-cdk-lib';
import * as eks from 'aws-cdk-lib/aws-eks';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface PlatformStackProps extends cdk.StackProps {
  readonly cluster: eks.ICluster;
  /** RDS master Secret (contains JSON with 'password' key). */
  readonly postgresSecret: secretsmanager.ISecret;
  /** Valkey AUTH token Secret, present only when valkeyTls=true. */
  readonly valkeyAuthSecret?: secretsmanager.ISecret;
  /** Hostname for the ACM cert. */
  readonly hostname: string;
}

const NAMESPACE = 'llmsafespaces';
const APP_SECRET_TAG = { 'llmsafespaces:role': 'app-secret' };

/**
 * Application-level resources:
 *
 *   - ACM public cert for `hostname` (DNS validation)
 *   - The `llmsafespaces` namespace
 *   - App-secret values in Secrets Manager: jwt, master, internal-token,
 *     inference-relay-secret. Each is generated by AWS once and stays
 *     stable across `cdk synth` and `cdk deploy` runs (fixes issue #1
 *     where the previous version regenerated these every synth).
 *   - A `ClusterSecretStore` + `ExternalSecret` (external-secrets.io)
 *     that materializes the `llmsafespaces-credentials` K8s Secret
 *     from the SM Secrets above plus the RDS + Valkey secrets from
 *     DataStack. This replaces the previous synth-time
 *     `unsafeUnwrap()` hack (issue #2) — the operator pod fetches
 *     resolved values at apply time, so the K8s Secret holds the real
 *     passwords, not CDK token strings.
 *
 * Helm install of the chart itself is still run manually after deploy.
 * See scripts/install-chart.sh.
 */
export class PlatformStack extends cdk.Stack {
  public readonly certificate: acm.ICertificate;

  constructor(scope: Construct, id: string, props: PlatformStackProps) {
    super(scope, id, props);

    this.certificate = new acm.Certificate(this, 'Cert', {
      domainName: props.hostname,
      validation: acm.CertificateValidation.fromDns(),
    });

    const appSecrets = this.buildAppSecrets();
    const namespace = this.buildNamespace(props.cluster);
    const secretStore = this.buildClusterSecretStore(props.cluster);

    const externalSecret = this.buildExternalSecret(
      props.cluster,
      props.postgresSecret,
      props.valkeyAuthSecret,
      appSecrets,
    );
    externalSecret.node.addDependency(namespace);
    externalSecret.node.addDependency(secretStore);

    this.emitOutputs(props.hostname);
  }

  /**
   * Generate the four app-level secrets in Secrets Manager. AWS owns
   * the random generation; values are stable across CDK synths because
   * SecretsManager itself is the source of truth (CDK only references
   * the ARN; the generated value lives in AWS forever unless the
   * Secret resource is replaced).
   *
   * Each is tagged with the IRSA-scoped tag so the external-secrets
   * controller can read them.
   */
  private buildAppSecrets(): {
    jwt: secretsmanager.Secret;
    master: secretsmanager.Secret;
    internalToken: secretsmanager.Secret;
    inferenceRelay: secretsmanager.Secret;
  } {
    const make = (id: string, description: string, length: number): secretsmanager.Secret => {
      const s = new secretsmanager.Secret(this, id, {
        description,
        generateSecretString: {
          passwordLength: length,
          excludePunctuation: true,
          excludeCharacters: '/@" ',
          includeSpace: false,
          requireEachIncludedType: false,
        },
        removalPolicy: cdk.RemovalPolicy.RETAIN,
      });
      for (const [k, v] of Object.entries(APP_SECRET_TAG)) {
        cdk.Tags.of(s).add(k, v);
      }
      return s;
    };

    return {
      jwt: make('JwtSecret', 'JWT signing key', 64),
      master: make('MasterSecret', 'Master encryption key', 64),
      internalToken: make('InternalToken', 'Internal API token', 32),
      inferenceRelay: make('InferenceRelaySecret', 'Inference relay secret', 32),
    };
  }

  private buildNamespace(cluster: eks.ICluster): eks.KubernetesManifest {
    return new eks.KubernetesManifest(this, 'Namespace', {
      cluster,
      manifest: [{
        apiVersion: 'v1',
        kind: 'Namespace',
        metadata: {
          name: NAMESPACE,
          // PSA `baseline` not `restricted` until lenaxia/LLMSafeSpaces#468
          // (frontend copy-html initContainer missing capabilities.drop).
          labels: {
            'pod-security.kubernetes.io/enforce': 'baseline',
            'pod-security.kubernetes.io/audit': 'restricted',
            'pod-security.kubernetes.io/warn': 'restricted',
          },
        },
      }],
      overwrite: true,
      prune: false,
    });
  }

  /**
   * ClusterSecretStore (external-secrets.io) configured to use the
   * IRSA role for SM access. Cluster-scoped so we don't have to repeat
   * it per namespace.
   *
   * The `role` prop is intentionally NOT set: IRSA binds the role to
   * the operator's ServiceAccount via the eks.amazonaws.com/role-arn
   * annotation (configured in ClusterStack's Helm install). ESO uses
   * the pod's bound credentials automatically.
   */
  private buildClusterSecretStore(
    cluster: eks.ICluster,
  ): eks.KubernetesManifest {
    return new eks.KubernetesManifest(this, 'ClusterSecretStore', {
      cluster,
      manifest: [{
        apiVersion: 'external-secrets.io/v1beta1',
        kind: 'ClusterSecretStore',
        metadata: { name: 'aws-sm' },
        spec: {
          provider: {
            aws: {
              service: 'SecretsManager',
              region: cdk.Stack.of(cluster as Construct).region,
              auth: {
                jwt: {
                  serviceAccountRef: {
                    name: 'external-secrets',
                    namespace: 'external-secrets',
                  },
                },
              },
            },
          },
        },
      }],
      overwrite: true,
      prune: false,
    });
  }

  /**
   * ExternalSecret resource that materializes the
   * `llmsafespaces-credentials` K8s Secret from SM. The chart's
   * `externalSecret.existingSecret` points at this Secret name.
   *
   * Maps each SM Secret to a key in the K8s Secret:
   *   postgres-password         <- {postgresSecret}/password
   *   redis-password            <- {valkeyAuthSecret}/AUTHTOKEN  (only if TLS)
   *   jwt-secret                <- {jwtSecret}
   *   master-secret             <- {masterSecret}
   *   internal-token            <- {internalToken}
   *   inference-relay-secret    <- {inferenceRelaySecret}
   */
  private buildExternalSecret(
    cluster: eks.ICluster,
    postgresSecret: secretsmanager.ISecret,
    valkeyAuthSecret: secretsmanager.ISecret | undefined,
    app: ReturnType<PlatformStack['buildAppSecrets']>,
  ): eks.KubernetesManifest {
    const data: Array<Record<string, unknown>> = [
      {
        secretKey: 'postgres-password',
        remoteRef: { key: postgresSecret.secretArn, property: 'password' },
      },
      {
        secretKey: 'jwt-secret',
        remoteRef: { key: app.jwt.secretArn },
      },
      {
        secretKey: 'master-secret',
        remoteRef: { key: app.master.secretArn },
      },
      {
        secretKey: 'internal-token',
        remoteRef: { key: app.internalToken.secretArn },
      },
      {
        secretKey: 'inference-relay-secret',
        remoteRef: { key: app.inferenceRelay.secretArn },
      },
    ];

    if (valkeyAuthSecret) {
      data.push({
        secretKey: 'redis-password',
        remoteRef: { key: valkeyAuthSecret.secretArn },
      });
    }

    // Postgres + Valkey secrets are tagged in DataStack (where they're
    // created); doing it here is a no-op because they're cross-stack
    // ISecret refs and CDK's tag propagation won't reach the actual
    // SM resources.

    return new eks.KubernetesManifest(this, 'CredentialsExternalSecret', {
      cluster,
      manifest: [{
        apiVersion: 'external-secrets.io/v1beta1',
        kind: 'ExternalSecret',
        metadata: {
          name: 'llmsafespaces-credentials',
          namespace: NAMESPACE,
        },
        spec: {
          // Refresh hourly. Workspace pods cache resolved secrets so
          // a 1h staleness window is fine.
          refreshInterval: '1h',
          secretStoreRef: {
            kind: 'ClusterSecretStore',
            name: 'aws-sm',
          },
          target: {
            name: 'llmsafespaces-credentials',
            creationPolicy: 'Owner',
            // Preserve through helm uninstall (chart references this Secret
            // by name; if it's deleted the chart's pre-install hook
            // re-generates with wrong values).
            template: {
              metadata: {
                annotations: { 'helm.sh/resource-policy': 'keep' },
              },
              type: 'Opaque',
            },
          },
          data,
        },
      }],
      overwrite: true,
      prune: false,
    });
  }

  private emitOutputs(hostname: string): void {
    new cdk.CfnOutput(this, 'CertArn', { value: this.certificate.certificateArn });
    new cdk.CfnOutput(this, 'CertDomain', { value: hostname });
    new cdk.CfnOutput(this, 'CertValidationNote', {
      value: 'In ACM console -> the pending cert: copy the CNAME and add at your DNS provider. CFN waits up to ~25min for validation.',
    });
    new cdk.CfnOutput(this, 'HelmInstallNote', {
      value: 'After cdk deploy --all completes, run scripts/install-chart.sh',
    });
  }
}
